services:
  ner:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: x5_ner
    ports:
      - "8080:8080"
    environment:
      - MODEL_DIR=/app/data/models/
      - MAX_LEN=10
      - MAX_BATCH=24
      - MAX_WAIT_MS=6
      - WORKERS=2
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - ORT_NUM_THREADS=1
    restart: unless-stopped
